In [2]:
import torch

In [3]:
scalar=torch.tensor(7)
print(scalar)
print(scalar.ndim) # a scalar is zero dimensional
print(scalar.item()) # torch.tensor to python integer

tensor(7)
0
7


In [4]:
vector=torch.tensor([7,7])
print(vector)
print(vector.ndim) # number of dimensions of a tensor = number of square brackets on the outside
print(vector.shape) # shape [2]

tensor([7, 7])
1
torch.Size([2])


In [5]:
matrix=torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
TENSOR=torch.tensor(
    [[[1,2,3],[3,6,9],[2,4,5]]]
)

print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


(a) scalar - a single number - 0  
(b) vector - a number with direction - 1  
(c) matrix - a 2-dimensional array of numbers - 2  
(d) tensor -  a n-dimensional array of numbers - can be any number, a 0 dimension tensor is a scalar, a 1 dimensional tensor is a vector

##### Random Tensors  
tensors represent some form of data & ml models such as neural networks manipulate and seek patterns within tensors.  
  
a ml model starts out with large random tensors of numbers and adjust these random numbers as it works through data to better represent it. 
   
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...  
  
  




In [7]:
#random tensors
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.3143, 0.0310, 0.5324, 0.7390],
         [0.2624, 0.1397, 0.4876, 0.0519],
         [0.0441, 0.1769, 0.8831, 0.9077]]),
 torch.float32)

In [9]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.dtype

(torch.Size([224, 224, 3]), torch.float32)

In [10]:
#Zeros and ones
zeros=torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones=torch.ones(size=(5,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [12]:
zero_to_ten_deprecated=torch.range(0,10)

zero_to_ten=torch.arange(start=0,end=10,step=1)
zero_to_ten

/var/folders/7j/6p_pd3gd44zfw3nn6n10_pnh0000gn/T/ipykernel_4208/462883564.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated=torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### Tensor datatypes  
distinct tensor datatypes specific for CPU and for GPU  
torch.cuda -> tensor is being used for a GPU  
most common type -> torch.float32 or torch.float  



In [14]:
# Default datatype for tensors is float32
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [15]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [19]:
# what shape, what data-type, where stored?
some_tensor=torch.rand(3,4)
print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.4653, 0.8879, 0.0382, 0.6343],
        [0.0251, 0.1027, 0.2806, 0.6108],
        [0.6603, 0.5544, 0.0473, 0.9220]])
torch.Size([3, 4])
torch.float32
cpu


### Mainpulating Tensors (tensor operations)

In [20]:
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [21]:
tensor *10

tensor([10, 20, 30])

In [22]:
tensor

tensor([1, 2, 3])

In [24]:
tensor=tensor-10
tensor

tensor([-19, -18, -17])

In [25]:
torch.multiply(tensor,10)

tensor([-190, -180, -170])

In [26]:
tensor

tensor([-19, -18, -17])

In [27]:
tensor=torch.tensor([1,2,3])

In [30]:
tensor*tensor # element wise multiplication

tensor([1, 4, 9])

In [31]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [32]:
tensor @ tensor

tensor(14)

In [33]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [34]:
tensor_A@tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [35]:
tensor_A.T@tensor_B

tensor([[ 76., 103.],
        [100., 136.]])

torch.nn.Linear() -> feedforward layer or fully connected layer, implements matrix multiplication between an input x and a weights matrix A

$$ y = x\cdot{A^T} + b $$

In [36]:
torch.manual_seed(42)
#this uses matrix multiplication
linear=torch.nn.Linear(in_features=2, out_features=6)

x=tensor_A
output=linear(x)
print(f"input shape: {x.shape}")
print(f"Output:{output}")
print(f"Ouput shape:{output.shape}")


input shape: torch.Size([3, 2])
Output:tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Ouput shape:torch.Size([3, 6])


In [37]:
tensor_A.shape

torch.Size([3, 2])

In [38]:
torch.manual_seed(42)
#this uses matrix multiplication
linear=torch.nn.Linear(in_features=3, out_features=6)

x=tensor_A
output=linear(x)
print(f"input shape: {x.shape}")
print(f"Output:{output}")
print(f"Ouput shape:{output.shape}")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x6)

In [39]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
print(f"min:{x.min()}")
print(f"max:{x.max()}")

min:0
max:90


In [41]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
print(tensor.argmax())
print(tensor.argmin())

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(8)
tensor(0)


### Reshaping, stacking, squeezing and unsqueezing

In [49]:
#torch.reshape(input,shape)
x=torch.arange(1.,8.)
print(x,x.shape)
x_reshaped=x.reshape(1,7)
print(x_reshaped,x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


In [51]:
#tensor.view(shape)->view of the original tensor in a diff shape but shares the same data as the original tensor
# Change view (keeps same data as original but changes view)
z=x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [53]:
#torch.stack(tensors,dim=0) > concatenates a sequence of tensors along a new dim, all tensors must be of the same size
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [54]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [57]:
#torch.squeez(input) squeezes input to remove all dimensions with value 1
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed=x_reshaped.squeeze()
x_squeezed,x_squeezed.shape


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])


(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [58]:
#torch.unsqueez(input, dim) returns input with a dim value 1 added at dim 
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [59]:
#torch.permute(input, dims) - view of the original input with its dims permuted(rearranged) to dims
x_original = torch.rand(size=(224, 224, 3))


# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the origina

### Indexing

In [60]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [64]:
x[:,0]

tensor([[1, 2, 3]])

In [65]:
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
x[:,1,1]

tensor([5])

In [67]:
x[0,0,:]

tensor([1, 2, 3])

### Pytorch tensors & numpy

In [69]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [71]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [72]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

start with random numbers -> tensor operations -> try to make better (again and again and again)

In [73]:
import torch

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

Tensor B:
tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [74]:
import torch
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED) 
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [75]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [76]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [77]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [78]:
device

'mps'

In [79]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [80]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [81]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])